In [28]:
import numpy as np
from numpy import linalg as LA

In [2]:
def puntos_interseccion(array_imagen):
    grid = [(0,0),(1,1),(1,0)]
    resultado = []
    for (y,x) in grid:
        resultado.append([y,x]+list(array_imagen[y][x]))
    return np.array(resultado)

In [3]:
arr1=[1,1]
array_im=[250,10,25]
np.array(arr1+array_im)

array([  1,   1, 250,  10,  25])

In [4]:
result =  []
result.append(np.array(arr1+array_im))

In [6]:
ds=puntos_interseccion(np.array([[[45,45,45],[55,55,55]],[[45,45,45],[55,55,55]]]))

In [40]:
np.array([[45,45,45],[55,55,55]])

array([[45, 45, 45],
       [55, 55, 55]])

In [7]:
ds

array([[ 0,  0, 45, 45, 45],
       [ 1,  1, 55, 55, 55],
       [ 1,  0, 45, 45, 45]])

In [8]:
np.array([0,0,45,55,45])-ds

array([[  0,   0,   0,  10,   0],
       [ -1,  -1, -10,   0, -10],
       [ -1,   0,   0,  10,   0]])

In [9]:
def shift_point(point,points,bw_s,bw_r):
    

SyntaxError: unexpected EOF while parsing (<ipython-input-9-564ea2b84b1b>, line 2)

In [10]:
ds

array([[ 0,  0, 45, 45, 45],
       [ 1,  1, 55, 55, 55],
       [ 1,  0, 45, 45, 45]])

In [58]:
vals = np.array([LA.norm((1-ds[:,:2]/0.2)[i]) for i in range(len(1-ds[:,:2]/0.2)) ])

In [42]:
len(1-ds[:,:2]/0.2)

3

In [50]:
2*np.array([2,3])*np.array([3,4])

array([12, 24])

In [59]:
np.array([1-x if abs(x)<=1 else 0 for x in vals])

array([0, 0, 0])